#!/usr/bin/env bash
# subdomains info

domain_name=$1
if [ "$#" -eq 2 ]; then
	sub=("www" "lb-01" "web-01" "web-02")
else
   sub=$2
fi
for subdomain in ${sub[@]}; do
    record_type="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    destination_ip="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo -n "The subdomain $subdomain"
done
