#!/usr/bin/env bash
# subdomains info

domain_name=$1
if [ "$#" -eq 1 ]; then
	sub=("www" "lb-01" "web-01" "web-02")
fi
for subdomain in ${sub[@]}; do
    record_type="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    destination_ip="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo "The subdomain $subdomain is a $record_type record and points to $destination_ip"
done
else
    sub=$2
done
